language: node_js

node_js:
  - node

jobs:
  include:
    - stage: tests
      script:
        - npm run build
        - npm test

    - stage: deployment
      install: skip
      script: skip
      deploy:
        provider: script
        script: bash .travis-deploy.sh
        on:
          branch: production

    - stage: deployment
      install: skip
      script: skip
      deploy:
        provider: script
        script: bash .travis-deploy-test.sh
        on:
          all_branches: true
          condition: $TRAVIS_BRANCH != ^production$
